
# Filtering Content
future: false

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
highlighter: pygments

# Outputting
permalink:     /post/:title/
paginate_path: /:num
paginate:	   100
timezone:      null

quiet:    false
defaults: []


theme:
  name: "TOM HEWITT"
  title: "Tom Does Digital"
  description: "A blog... it's my blog..."

  # THEME ICONS
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance: "tomchewitt"
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "tomchewitt"
  google_plus:
  instagram:
  linkedin: "http://uk.linkedin.com/in/tomphewitt" # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  tumblr:
  twitter: "twitter"
  wordpress:
  youtube:

  # THEME SCRIPTS
  google_analytics: "UA-16424514-4"
  disqus_shortname: "tomchewitt"
