theme: 
  # GLOBALS
  name: "Blogname is Blog Name"
  description: "A blog... it's my blog..."

  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "tomchewitt"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "twitter"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
# markdown: markdown
highlighter: pygments
exclude: ["node_modules", "src", "Gruntfile.js", "package.json"]